//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AgregationClassService } from '@/services/AgregationClass.service';
import { IBaseAgregationClass } from '@/types/AgregationClass.types';

const useCreateAgregationClass = <T extends IBaseAgregationClass>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type CreateRecordArgs = {
    agregationClass: T;
    viewName: string;
  };

  const {
    mutate: createAgregationClass,
    mutateAsync: createAgregationClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (createRecordArgs: CreateRecordArgs) =>
      AgregationClassService.CreateAgregationClass<T>(createRecordArgs.agregationClass, createRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'agregationClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { createAgregationClass, createAgregationClassAsync, isPending };
};

export default useCreateAgregationClass;
