//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AgregationClassService } from '@/services/AgregationClass.service';

const useDeleteAllAgregationClass = (
  onSuccess: (result: string[]) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAllAgregationClass,
    mutateAsync: deleteAllAgregationClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (ids: string[]) => AgregationClassService.DeleteAllAgregationClass(ids),
    onSuccess: (_, ids) => {
      const className = 'agregationClass';
      ids.forEach((id) => {
        queryClient.removeQueries({ queryKey: [className, id] });
      });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(ids);
    },
    onError: (e) => onError(e),
  });

  return { deleteAllAgregationClass, deleteAllAgregationClassAsync, isPending };
};

export default useDeleteAllAgregationClass;
