//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AgregationClassService } from '@/services/AgregationClass.service';
import { IBaseAgregationClass } from '@/types/AgregationClass.types';

const useUpdateAgregationClass = <T extends IBaseAgregationClass>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    agregationClass: T;
    viewName: string;
  };

  const {
    mutate: updateAgregationClass,
    mutateAsync: updateAgregationClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      AgregationClassService.UpdateAgregationClass<T>(updateRecordArgs.agregationClass, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'agregationClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateAgregationClass, updateAgregationClassAsync, isPending };
};

export default useUpdateAgregationClass;
