//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { ClassEnum } from '../enums/ClassEnum.types';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseAgregationClass {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseAgregationClass custom)

  // *** End programmer edit section *** (IBaseAgregationClass custom)
}

export interface IAggregationD extends IBaseAgregationClass {
  aggregation: string;
  classAddress: string;
  className: ClassEnum;
  classAssosiationClassAssosiationName: string;
  // *** Start programmer edit section *** (IAggregationD custom)

  // *** End programmer edit section *** (IAggregationD custom)
}

export interface IAggregationE extends IBaseAgregationClass {
  aggregation: string;
  // *** Start programmer edit section *** (IAggregationE custom)

  // *** End programmer edit section *** (IAggregationE custom)
}

export interface IAggregationL extends IBaseAgregationClass {
  aggregation: string;
  // *** Start programmer edit section *** (IAggregationL custom)

  // *** End programmer edit section *** (IAggregationL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
