//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Test.WebAPI.Controllers
{
    using System;
    using System.Text.Json;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Unity;
    using Test.ApplicationLayer.DTO;
    using Test.ApplicationLayer.DTO.AggregationClass;
    using Test.ApplicationLayer.DTO.AssosiationClass;
    using Test.ApplicationLayer.DTO.Class;
    using Test.ApplicationLayer.DTO.ClassTest;
    using Test.ApplicationLayer.ExportProviders;

    /// <summary>
    /// Контроллер экспорта списковых форм в Excel.
    /// </summary>
    [ApiController]
    [Route("export")]
    public class ExportController : ControllerBase
    {
        private readonly IUnityContainer _container;

        public ExportController(IUnityContainer container)
        {
            _container = container;
        }

        /// <summary>
        /// Экспорт AggregationL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("AggregationL")]
        public async Task<IActionResult> ExportAggregationL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] AggregationLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<AggregationClassDtoBase> provider = _container.Resolve<IExcelExportProvider<AggregationClassDtoBase>>("AggregationLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<AggregationLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "AggregationL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Экспорт AssosiationClassL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("AssosiationClassL")]
        public async Task<IActionResult> ExportAssosiationClassL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] AssosiationClassLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<AssosiationClassDtoBase> provider = _container.Resolve<IExcelExportProvider<AssosiationClassDtoBase>>("AssosiationClassLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<AssosiationClassLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "AssosiationClassL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Экспорт ClassL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("ClassL")]
        public async Task<IActionResult> ExportClassL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] ClassLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<ClassDtoBase> provider = _container.Resolve<IExcelExportProvider<ClassDtoBase>>("ClassLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<ClassLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "ClassL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Экспорт ClassTestL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("ClassTestL")]
        public async Task<IActionResult> ExportClassTestL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] ClassTestLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<ClassTestDtoBase> provider = _container.Resolve<IExcelExportProvider<ClassTestDtoBase>>("ClassTestLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<ClassTestLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "ClassTestL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}
