




CREATE TABLE InheritanceClass (
 primaryKey UUID NOT NULL,
 Inheritance VARCHAR(255) NULL,
 Address VARCHAR(255) NULL,
 Name VARCHAR(6) NULL,
 AssosiationClass UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Class (
 primaryKey UUID NOT NULL,
 Address VARCHAR(255) NULL,
 Name VARCHAR(6) NULL,
 AssosiationClass UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE AgregationClass (
 primaryKey UUID NOT NULL,
 Aggregation VARCHAR(255) NULL,
 Class_m0 UUID NULL,
 Class_m1 UUID NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE AssosiationClass (
 primaryKey UUID NOT NULL,
 AssosiationName VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE InheritanceClass ADD CONSTRAINT FK606c7d89361aeb6453390c2dd7d9baa14305908a FOREIGN KEY (AssosiationClass) REFERENCES AssosiationClass; 
CREATE INDEX Index606c7d89361aeb6453390c2dd7d9baa14305908a on InheritanceClass (AssosiationClass); 

 ALTER TABLE Class ADD CONSTRAINT FK38354ca86ee9149cc5c514ec297e3f4aeb8b963a FOREIGN KEY (AssosiationClass) REFERENCES AssosiationClass; 
CREATE INDEX Index38354ca86ee9149cc5c514ec297e3f4aeb8b963a on Class (AssosiationClass); 

 ALTER TABLE AgregationClass ADD CONSTRAINT FK9083d4d7bfd8715ba51f6dcdb0edc48cb32e280c FOREIGN KEY (Class_m0) REFERENCES Class; 
CREATE INDEX Index9083d4d7bfd8715ba51f6dcdb0edc48cb32e280c on AgregationClass (Class_m0); 

 ALTER TABLE AgregationClass ADD CONSTRAINT FK32c2d94bebf91d0c98283edf9cd8f1270910dd14 FOREIGN KEY (Class_m1) REFERENCES InheritanceClass; 
CREATE INDEX Index32c2d94bebf91d0c98283edf9cd8f1270910dd14 on AgregationClass (Class_m1); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

