//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Test.ApplicationLayer.DTO.AgregationClass
{
    using System;
    using ICSSoft.STORMNET;
    using Test;
    using Test.ApplicationLayer;
    using Test.ApplicationLayer.Attributes;
    using Test.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления AgregationClass.AggregationL.
    /// </summary>
    [DataView(typeof(AgregationClass), "AggregationL")]
    public partial class AggregationLDto : AgregationClassDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AggregationLDto"/>.
        /// </summary>
        public AggregationLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AggregationLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public AggregationLDto(AgregationClass source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Aggregation.
        /// </summary>
        [PropertyName("Aggregation")]
        [CaptionProperty("Aggregation")]
        public string Aggregation { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override AggregationLDto FillFromClass(AgregationClass source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Aggregation = source.Aggregation;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(AgregationClass destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Aggregation = Aggregation;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
