//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseAgregationClass } from '@/types/AgregationClass.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const AgregationClassService = {
  async GetAllAgregationClass(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/agregationclass/${viewName}${queryStr}`);
  },

  async GetAgregationClass(id: string, viewName: string) {
    return await axiosInstance.get(`/agregationclass/${viewName}/${id}`);
  },

  async CreateAgregationClass<T extends IBaseAgregationClass>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/agregationclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateAgregationClass<T extends IBaseAgregationClass>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/agregationclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteAgregationClass(id: string) {
    return await axiosInstance.delete(`/agregationclass/${id}`);
  },

  async DeleteAllAgregationClass(ids: string[]) {
    return await axiosInstance.post(`/agregationclass/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/agregationclass/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
