//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
export enum tView {
  AggregationD = 'AggregationD',
  AggregationE = 'AggregationE',
  AggregationL = 'AggregationL',
  AssosiationClassE = 'AssosiationClassE',
  AssosiationClassL = 'AssosiationClassL',
  ClassE = 'ClassE',
  ClassL = 'ClassL',
  ClassTestE = 'ClassTestE',
  ClassTestL = 'ClassTestL',
  InheritanceClassE = 'InheritanceClassE',
  InheritanceClassL = 'InheritanceClassL',
  // *** Start programmer edit section *** (Additional views)

  // *** End programmer edit section *** (Additional views)
}
