//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// AgregationClass.
    /// </summary>
    // *** Start programmer edit section *** (AgregationClass CustomAttributes)

    // *** End programmer edit section *** (AgregationClass CustomAttributes)
    [AutoAltered()]
    [Caption("AgregationClass")]
    [View("AggregationD", new string[] {
            "Aggregation as \'Aggregation\'",
            "Class.Address as \'Class.Address\'",
            "Class.Name as \'Class.Name\'",
            "Class.AssosiationClass.AssosiationName as \'Class.AssosiationClass.AssosiationName\'"})]
    [View("AggregationE", new string[] {
            "Aggregation as \'Aggregation\'"})]
    [View("AggregationL", new string[] {
            "Aggregation as \'Aggregation\'"})]
    public class AgregationClass : ICSSoft.STORMNET.DataObject
    {

        private string fAggregation;

        private Test.Class fClass;

        // *** Start programmer edit section *** (AgregationClass CustomMembers)

        // *** End programmer edit section *** (AgregationClass CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (AgregationClass.Aggregation CustomAttributes)

        // *** End programmer edit section *** (AgregationClass.Aggregation CustomAttributes)
        public virtual string Aggregation
        {
            get
            {
                // *** Start programmer edit section *** (AgregationClass.Aggregation Get start)

                // *** End programmer edit section *** (AgregationClass.Aggregation Get start)
                string result = this.fAggregation;
                // *** Start programmer edit section *** (AgregationClass.Aggregation Get end)

                // *** End programmer edit section *** (AgregationClass.Aggregation Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AgregationClass.Aggregation Set start)

                // *** End programmer edit section *** (AgregationClass.Aggregation Set start)
                this.fAggregation = value;
                // *** Start programmer edit section *** (AgregationClass.Aggregation Set end)

                // *** End programmer edit section *** (AgregationClass.Aggregation Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (AgregationClass.Class CustomAttributes)

        // *** End programmer edit section *** (AgregationClass.Class CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Class"})]
        public virtual Test.Class Class
        {
            get
            {
                // *** Start programmer edit section *** (AgregationClass.Class Get start)

                // *** End programmer edit section *** (AgregationClass.Class Get start)
                Test.Class result = this.fClass;
                // *** Start programmer edit section *** (AgregationClass.Class Get end)

                // *** End programmer edit section *** (AgregationClass.Class Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AgregationClass.Class Set start)

                // *** End programmer edit section *** (AgregationClass.Class Set start)
                this.fClass = value;
                // *** Start programmer edit section *** (AgregationClass.Class Set end)

                // *** End programmer edit section *** (AgregationClass.Class Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AggregationD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AggregationD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AggregationD", typeof(Test.AgregationClass));
                }
            }

            /// <summary>
            /// "AggregationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AggregationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AggregationE", typeof(Test.AgregationClass));
                }
            }

            /// <summary>
            /// "AggregationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AggregationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AggregationL", typeof(Test.AgregationClass));
                }
            }
        }

    }

    /// <summary>
    /// Detail array of AgregationClass.
    /// </summary>
    public class DetailArrayOfAgregationClass : ICSSoft.STORMNET.DetailArray
    {
        /// <summary>
        /// Construct detail array.
        /// </summary>
        public DetailArrayOfAgregationClass(Test.Class fClass) :
                base(typeof(AgregationClass), ((ICSSoft.STORMNET.DataObject)(fClass)))
        {
        }

        /// <summary>
        /// Returns object with type AgregationClass by index.
        /// </summary>
        public Test.AgregationClass this[int index]
        {
            get
            {
                return ((Test.AgregationClass)(this.ItemByIndex(index)));
            }
        }

        /// <summary>
        /// Adds object with type AgregationClass.
        /// </summary>
        public virtual void Add(Test.AgregationClass dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
