//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Class.
    /// </summary>
    // *** Start programmer edit section *** (Class CustomAttributes)

    // *** End programmer edit section *** (Class CustomAttributes)
    [AutoAltered()]
    [Caption("Class")]
    [View("ClassE", new string[] {
            "Address as \'Address\'",
            "Name as \'Name\'",
            "AssosiationClass.AssosiationName as \'AssosiationClass.AssosiationName\'"})]
    [View("ClassL", new string[] {
            "Address as \'Address\'",
            "Name as \'Name\'"})]
    public class Class : ICSSoft.STORMNET.DataObject
    {

        private string fAddress;

        private ClassEnum fName;

        private Test.AssosiationClass fAssosiationClass;

        private Test.DetailArrayOfAgregationClass fAgregationClass;

        // *** Start programmer edit section *** (Class CustomMembers)

        // *** End programmer edit section *** (Class CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Class.Address CustomAttributes)

        // *** End programmer edit section *** (Class.Address CustomAttributes)
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (Class.Address Get start)

                // *** End programmer edit section *** (Class.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (Class.Address Get end)

                // *** End programmer edit section *** (Class.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class.Address Set start)

                // *** End programmer edit section *** (Class.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Class.Address Set end)

                // *** End programmer edit section *** (Class.Address Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Class.Name CustomAttributes)

        // *** End programmer edit section *** (Class.Name CustomAttributes)
        public virtual ClassEnum Name
        {
            get
            {
                // *** Start programmer edit section *** (Class.Name Get start)

                // *** End programmer edit section *** (Class.Name Get start)
                ClassEnum result = this.fName;
                // *** Start programmer edit section *** (Class.Name Get end)

                // *** End programmer edit section *** (Class.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class.Name Set start)

                // *** End programmer edit section *** (Class.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Class.Name Set end)

                // *** End programmer edit section *** (Class.Name Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Class.AssosiationClass CustomAttributes)

        // *** End programmer edit section *** (Class.AssosiationClass CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "AssosiationClass"})]
        public virtual Test.AssosiationClass AssosiationClass
        {
            get
            {
                // *** Start programmer edit section *** (Class.AssosiationClass Get start)

                // *** End programmer edit section *** (Class.AssosiationClass Get start)
                Test.AssosiationClass result = this.fAssosiationClass;
                // *** Start programmer edit section *** (Class.AssosiationClass Get end)

                // *** End programmer edit section *** (Class.AssosiationClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class.AssosiationClass Set start)

                // *** End programmer edit section *** (Class.AssosiationClass Set start)
                this.fAssosiationClass = value;
                // *** Start programmer edit section *** (Class.AssosiationClass Set end)

                // *** End programmer edit section *** (Class.AssosiationClass Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Class.AgregationClass CustomAttributes)

        // *** End programmer edit section *** (Class.AgregationClass CustomAttributes)
        [PropertyStorage(new string[] {
                "Class"})]
        public virtual Test.DetailArrayOfAgregationClass AgregationClass
        {
            get
            {
                // *** Start programmer edit section *** (Class.AgregationClass Get start)

                // *** End programmer edit section *** (Class.AgregationClass Get start)
                if ((this.fAgregationClass == null))
                {
                    this.fAgregationClass = new Test.DetailArrayOfAgregationClass(this);
                }
                Test.DetailArrayOfAgregationClass result = this.fAgregationClass;
                // *** Start programmer edit section *** (Class.AgregationClass Get end)

                // *** End programmer edit section *** (Class.AgregationClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Class.AgregationClass Set start)

                // *** End programmer edit section *** (Class.AgregationClass Set start)
                this.fAgregationClass = value;
                // *** Start programmer edit section *** (Class.AgregationClass Set end)

                // *** End programmer edit section *** (Class.AgregationClass Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ClassE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClassE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClassE", typeof(Test.Class));
                }
            }

            /// <summary>
            /// "ClassL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClassL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClassL", typeof(Test.Class));
                }
            }
        }

    }
}
