//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// InheritanceClass.
    /// </summary>
    // *** Start programmer edit section *** (InheritanceClass CustomAttributes)

    // *** End programmer edit section *** (InheritanceClass CustomAttributes)
    [AutoAltered()]
    [Caption("InheritanceClass")]
    [View("InheritanceClassE", new string[] {
            "Name",
            "Address",
            "Inheritance"})]
    [View("InheritanceClassL", new string[] {
            "Address as \'Address\'",
            "Inheritance as \'Inheritance\'",
            "Name as \'Name\'"})]
    public class InheritanceClass : ICSSoft.STORMNET.DataObject
    {

        private string fAddress;

        private string fInheritance;

        private ClassEnum fName;

        private Test.AssosiationClass fAssosiationClass;

        private Test.DetailArrayOfAgregationClass fAgregationClass;

        // *** Start programmer edit section *** (InheritanceClass CustomMembers)

        // *** End programmer edit section *** (InheritanceClass CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (InheritanceClass.Address CustomAttributes)

        // *** End programmer edit section *** (InheritanceClass.Address CustomAttributes)
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (InheritanceClass.Address Get start)

                // *** End programmer edit section *** (InheritanceClass.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (InheritanceClass.Address Get end)

                // *** End programmer edit section *** (InheritanceClass.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InheritanceClass.Address Set start)

                // *** End programmer edit section *** (InheritanceClass.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (InheritanceClass.Address Set end)

                // *** End programmer edit section *** (InheritanceClass.Address Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (InheritanceClass.Inheritance CustomAttributes)

        // *** End programmer edit section *** (InheritanceClass.Inheritance CustomAttributes)
        public virtual string Inheritance
        {
            get
            {
                // *** Start programmer edit section *** (InheritanceClass.Inheritance Get start)

                // *** End programmer edit section *** (InheritanceClass.Inheritance Get start)
                string result = this.fInheritance;
                // *** Start programmer edit section *** (InheritanceClass.Inheritance Get end)

                // *** End programmer edit section *** (InheritanceClass.Inheritance Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InheritanceClass.Inheritance Set start)

                // *** End programmer edit section *** (InheritanceClass.Inheritance Set start)
                this.fInheritance = value;
                // *** Start programmer edit section *** (InheritanceClass.Inheritance Set end)

                // *** End programmer edit section *** (InheritanceClass.Inheritance Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (InheritanceClass.Name CustomAttributes)

        // *** End programmer edit section *** (InheritanceClass.Name CustomAttributes)
        public virtual ClassEnum Name
        {
            get
            {
                // *** Start programmer edit section *** (InheritanceClass.Name Get start)

                // *** End programmer edit section *** (InheritanceClass.Name Get start)
                ClassEnum result = this.fName;
                // *** Start programmer edit section *** (InheritanceClass.Name Get end)

                // *** End programmer edit section *** (InheritanceClass.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InheritanceClass.Name Set start)

                // *** End programmer edit section *** (InheritanceClass.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (InheritanceClass.Name Set end)

                // *** End programmer edit section *** (InheritanceClass.Name Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (InheritanceClass.AssosiationClass CustomAttributes)

        // *** End programmer edit section *** (InheritanceClass.AssosiationClass CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "AssosiationClass"})]
        public virtual Test.AssosiationClass AssosiationClass
        {
            get
            {
                // *** Start programmer edit section *** (InheritanceClass.AssosiationClass Get start)

                // *** End programmer edit section *** (InheritanceClass.AssosiationClass Get start)
                Test.AssosiationClass result = this.fAssosiationClass;
                // *** Start programmer edit section *** (InheritanceClass.AssosiationClass Get end)

                // *** End programmer edit section *** (InheritanceClass.AssosiationClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InheritanceClass.AssosiationClass Set start)

                // *** End programmer edit section *** (InheritanceClass.AssosiationClass Set start)
                this.fAssosiationClass = value;
                // *** Start programmer edit section *** (InheritanceClass.AssosiationClass Set end)

                // *** End programmer edit section *** (InheritanceClass.AssosiationClass Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (InheritanceClass.AgregationClass CustomAttributes)

        // *** End programmer edit section *** (InheritanceClass.AgregationClass CustomAttributes)
        [PropertyStorage(new string[] {
                "Class"})]
        public virtual Test.DetailArrayOfAgregationClass AgregationClass
        {
            get
            {
                // *** Start programmer edit section *** (InheritanceClass.AgregationClass Get start)

                // *** End programmer edit section *** (InheritanceClass.AgregationClass Get start)
                if ((this.fAgregationClass == null))
                {
                    this.fAgregationClass = new Test.DetailArrayOfAgregationClass(this);
                }
                Test.DetailArrayOfAgregationClass result = this.fAgregationClass;
                // *** Start programmer edit section *** (InheritanceClass.AgregationClass Get end)

                // *** End programmer edit section *** (InheritanceClass.AgregationClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (InheritanceClass.AgregationClass Set start)

                // *** End programmer edit section *** (InheritanceClass.AgregationClass Set start)
                this.fAgregationClass = value;
                // *** Start programmer edit section *** (InheritanceClass.AgregationClass Set end)

                // *** End programmer edit section *** (InheritanceClass.AgregationClass Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "InheritanceClassE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View InheritanceClassE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("InheritanceClassE", typeof(Test.InheritanceClass));
                }
            }

            /// <summary>
            /// "InheritanceClassL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View InheritanceClassL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("InheritanceClassL", typeof(Test.InheritanceClass));
                }
            }
        }

    }
}
